import pyautogui as py
import webbrowser as wb
import pyperclip as pyp
from threading import Timer
import sys, os, time, random

run = "true"
password = ""
repo_name = ""
address = ""

def main_menu():
    global repo_name
    repo_name = input("Enter the repo name in the format \"username/reponame\": ")
    new_acc(1)

def new_acc(num_acc):
    global run
    global address
    for i in range(num_acc):
        wb.open('https://github.com/flancast90')
        time.sleep(2)
        py.hotkey('ctrl', 'l')
        time.sleep(0.2)
        py.write("chrome://settings/clearBrowserData")
        time.sleep(0.2)
        py.press('return')
        time.sleep(2)
        py.press('tab')
        time.sleep(0.2)
        py.press('tab')
        time.sleep(0.2)
        py.press('tab')
        time.sleep(0.2)
        py.press('tab')
        time.sleep(0.2)
        py.press('tab')
        time.sleep(0.2)
        py.press('tab')
        time.sleep(0.2)
        py.press('tab')
        time.sleep(0.2)
        py.press('tab')
        time.sleep(0.2)
        py.press('return')
        time.sleep(3)
        py.hotkey('ctrl','t')
        time.sleep(1)
        py.write("https://10minutemail.net/")
        py.sleep(0.2)
        py.press('return')
        time.sleep(2)
        py.hotkey('ctrl', 'shift', 'j') 
        time.sleep(1)
        py.press('tab')
        time.sleep(1)
        py.write('var a = `%3Cinput value="`+document.getElementById("fe_text").value+`"/%3E`; var b = decodeURIComponent(a); document.write(b);')
        time.sleep(0.5)
        py.press('return')
        time.sleep(1)
        py.hotkey('ctrl', 'shift', 'j')
        time.sleep(1)
        py.press('tab')
        time.sleep(0.2)
        py.hotkey('ctrl', 'c')
        time.sleep(0.1)
        address = pyp.paste()
        py.hotkey('ctrl', 't')
        py.write("https://github.com/signup")
        py.press('return')
        time.sleep(4)
        py.write(address)
        time.sleep(1)
        py.press('return')
        time.sleep(1)
        py.hotkey('ctrl', 'shift', 'j')
        time.sleep(2)
        py.press('tab')
        time.sleep(0.2)
        py.write("document.getElementById('password').value = ''; document.getElementById('password').focus()")
        time.sleep(0.2)
        py.press('return')
        time.sleep(0.3)
        py.hotkey('ctrl', 'shift', 'j')
        time.sleep(1)
        py.write(pseudo_rand("pass")) 
        time.sleep(1)
        py.press('return')
        time.sleep(0.2)
        py.hotkey('ctrl', 'shift', 'j')
        time.sleep(2)
        py.press('tab')
        time.sleep(0.2)
        py.write("document.getElementById('login').value = ''; document.getElementById('login').focus();")
        time.sleep(0.2)
        py.press('return')
        time.sleep(0.3)
        py.hotkey('ctrl', 'shift', 'j') 
        time.sleep(1)
        py.write(pseudo_rand("uname"))
        time.sleep(1)
        py.press('return')
        time.sleep(1)
        py.write("y")
        time.sleep(1)
        py.press('return')
        py.press('tab')
        py.press('return')
        time.sleep(2)
        py.press('tab')
        print('Captcha detected. Please Solve.')
        py.hotkey('ctrl', 'shift', 'j')
        time.sleep(1)
        py.press('tab')
        time.sleep(1)
        py.write('var inter = setInterval(function(){ var element =  document.getElementsByClassName("form-control signup-submit-button width-full py-2 js-octocaptcha-form-submit")[0]; if (element.hidden == false) { element.click(); clearInterval(inter); } }, 1000);')
        py.press('return')
        while run == "true":
            time.sleep(2)
            py.hotkey('ctrl', 'l')
            py.hotkey('ctrl', 'c')
            url = pyp.paste()
            if url == "https://github.com/account_verifications":
                time.sleep(60)
                py.hotkey('ctrl', 't')
                py.write('https://10minutemail.net')
                py.press('return')
                time.sleep(2)
                py.hotkey('ctrl','shift','j')
                time.sleep(2)
                py.press('tab')
                time.sleep(0.2)
                py.write("document.getElementsByClassName('row-link')[0].click();")
                time.sleep(0.2)
                py.press('return')
                time.sleep(0.3)
                py.write('var a = `%3Cinput value="`+document.getElementsByClassName("branch-name f00-light text-gray-dark text-mono")[0].innerHTML+`"/%3E`; var b = decodeURIComponent(a); document.write(b);')
                time.sleep(0.2)
                py.press('return')
                time.sleep(0.3)
                py.hotkey('ctrl', 'shift', 'j')
                py.sleep(1)
                py.press('tab')
                time.sleep(0.2)
                py.hotkey('ctrl','c')
                time.sleep(0.2)
                py.hotkey('ctrl', 't')
                time.sleep(0.2)
                py.write('https://github.com/account_verifications')
                time.sleep(0.2)
                py.press('return')
                time.sleep(1)
                py.hotkey('ctrl', 'v')
                time.sleep(2)
                py.hotkey('ctrl','t')
                time.sleep(1)
                py.write('https://github.com/'+repo_name)
                time.sleep(0.2)
                py.press('return')
                time.sleep(1)
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('tab')
                py.press('return')
                run = "false"         

def pseudo_rand(args):
    if args == "uname":
        uname = ''.join(random.choice('qwertyuiopasdfghjklzxcvbnmQWRTYUIOPASDFGHJKLZXCVBNM124567890') for i in range(30))
        return uname
    elif args == "pass":
        global password
        passw = ''.join(random.choice('qwertyuiopasdfghjklzxcvbnmQWERTUIOPASDFGHJKLZXCVBNM1234567890.?!@#$%^&*()') for i in range(30))
        password = passw      
        return passw

main_menu()
